### ISSUE TITLE
Data received 5 times (Digoo DG-R8S)

### ISSUE THREAD

**Issue by chinswain** [dgomes/homeGW#8]
I have a Digoo DG-R8S  for testing - Every 60 seconds the example sketches output the same reading 5 times - is that expected?

**Comment by dgomes** [comment]
yes it is expected. Since these devices RF is quite unreliable, they retransmit the same message several times, and is up to you to figure out what to do. I have used different software algorithms in the past:
- Only take the value if all the retransmissions are equal
- Take the value of the most popular transmission (the one with more occurrences)
- Take the value of the one which makes more sense (em compared with previous values and physical limits)
